### ISSUE TITLE
Cannot compile on Ubuntu, missing dependency?

### ISSUE THREAD

**Issue by HongyiFan** [jizhaox/npt-pose#1]
Hi, I met an issue when compiling this code. My system is Ubuntu 18.04. 

After running CMake, I met two error messages:
1. FORTRAN_LIBRARY not found. 
2. MUMPS_LIBRARY4 not found. 

Then I manually set FORTRAN_LIBRARY = libgfortran.so, and MUMPS_LIBRARY5 = libmpiseq_seq.a 

After all these, when running demo, I got the following error: 
`
 ERROR in MPI_ALLREDUCE, DATATYPE=           7  
`

If I left MUMPS_LIBRARY4 as blank, I will get a bunch of error messages: 
`
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdmumps.a(dmumps_driver.o): In function dmumps_set_infog_:
(.text+0x69): undefined reference to mpi_allreduce_ 
`
I know it is some issue when installing SDPA, but any help or suggestion are appreciated. Thanks.

**Comment by jizhaox** [comment]
Please check whether SDPA has been installed successfully. I installed SDPA by compiling its source file. To check whether it has been installed successfully, you can compile and run the examples provided by SDPA source code. 

----------------------------------------------------------------------------------------------------------------------
The source code and install manual of SDPA can be found below.
http://sdpa.sourceforge.net/download.html
sdpa/sdpa_7.3.8.tar.gz
sdpa/sdpa-7.3.X-install.txt

**Comment by zhr5535** [comment]
> Hi, I met an issue when compiling this code. My system is Ubuntu 18.04.
> 
> After running CMake, I met two error messages:
> 
> 1. FORTRAN_LIBRARY not found.
> 2. MUMPS_LIBRARY4 not found.
> 
> Then I manually set FORTRAN_LIBRARY = libgfortran.so, and MUMPS_LIBRARY5 = libmpiseq_seq.a
> 
> After all these, when running demo, I got the following error: `ERROR in MPI_ALLREDUCE, DATATYPE= 7 `
> 
> If I left MUMPS_LIBRARY4 as blank, I will get a bunch of error messages: `/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdmumps.a(dmumps_driver.o): In function dmumps_set_infog_: (.text+0x69): undefined reference to mpi_allreduce_ ` I know it is some issue when installing SDPA, but any help or suggestion are appreciated. Thanks.

I encountered the same issue, and compiling sdpa from the source code doesn't seem to have resolved it. Have you managed to solve this problem? @HongyiFan
