### ISSUE TITLE
Combination with graduated non-convex does not work

### ISSUE THREAD

**Issue by hitdshu** [jizhaox/npt-pose#3]
Hi,

Thanks for your excellent work. I've reproduced your algorithm with MATLAB/C++ and got quite good results. 

However, when I combine the algorithm with GNC(Graduated non convex), I could not get meaningful results. Even with few outliers, the algorithm returns solutions that are not that good.

I use GM/TLS GNC to add weights to each point, and use the algebraic error "pj.dot(ess * pi)" as the cost. I also tried the sampson error. Could you please help me with it? Or could you release your code for the GNC?

Thanks very much,
Deshun

**Comment by jizhaox** [comment]
Hi,

I do have plan to release the code of GNC part. Since this code need refactoring, it might be finished a few weeks later. I will reply in this thread once it is released. You can contact me by email to discuss your code before that.

**Comment by hitdshu** [comment]
> Hi,
> 
> I do have plan to release the code of GNC part. Since this code need refactoring, it might be finished a few weeks later. I will reply in this thread once it is released. You can contact me by email to discuss your code before that.

Thanks. I'll extract some code and send it to you via email. Thanks for your help.

Deshun
